### ISSUE TITLE
7. What’s the most important thing we need to learn first?

### ISSUE THREAD

**Issue by cwalters126** [inspiredlab/inspiredlab.github.io#65]
For each hypothesis from Box 6, identify its riskiest assumptions.
Then determine the riskiest one right now. This is the assumption that will cause the entire idea to fail if it’s wrong.
(Hint: In the early stages of a hypothesis focus on risks to value rather than feasibility)

**Comment by cwalters126** [comment]
assumptions:

- the student likes and sees value our work
- the student wants to be a part of the team
- the student finds value in the workshop and doing the work required. 
- the student will reach out to us with questions about membership

**Comment by fedebassetti** [comment]
![image](https://user-images.githubusercontent.com/1824246/84797308-48031f80-afbf-11ea-8b0c-faa6557152f3.png)

**Comment by fedebassetti** [comment]
@leenabusalem @RaviHarsha @arturwhite1 @cwalters126 made some small changes in the template to highlight the tip.

In our case, we have a center assumption and then smaller assumptions. We need to make sure that everything in 6 is represented in 7.

Please share your feedback on this item. Think of your current situation a few months back when you heard about inspired lab. Think of what was that flow that helped with your decision. We need to represent it here, so that our web presence might help us in that direction.
