### ISSUE TITLE
Project Stories - MBIT

### ISSUE THREAD

**Issue by cwalters126** [inspiredlab/inspiredlab.github.io#88]
Find story about the MBIT project's first successful launch, tweak to fit the inspired lab website as a featured story

**Comment by fedebassetti** [comment]
HONORS CAPSTONE ABSTRACT
This capstone project initiated a partnership between the Department of Operations
Management and Information Systems (OM&IS) in the College of Business and the Huskie Marching
Band (HMB) where OM&IS students develop and implement technology solutions for the HMB to
decrease the time spent on administrative processes in order to focus on music and marching by
simplifying and centralizing existing processes.
The purpose of this project is to both assist the HMB in making their systems more efficient as
they grow in size as well as helping students of the OM&IS department develop technical skills
necessary to get ahead in their careers through real world experiences.
The methodology used for this project is the agile method. This software development method
will allow developers to track ideas for the system from simple ideas in a backlog, through
development, and into continual updating. The agile method is something that OM&IS students will
benefit from learning when going into careers with software development.
The scope of this project will remain within the realm of its purpose to decrease time for the
HMB with administrative tasks. The tasks completed for this project now, or in the future, include
audition voting, evaluations, attendance, uniform inventory, and more.
Over the past year and a half, there has been a lot of progress made on this project. The
organizational structure and communication channels have been put into place. The organization now
has a following of members who will continue to contribute to the project. Some of the processes of
the HMB have already been digitally transformed once or even twice. To give some measurements:
the audition voting system saved 4.5 hours on calculations, and the uniform fitting inventory
management system cut the normal 3 days spent fitting uniforms in half. Neither of these systems are
in their final stages, but simply were switched from paper documents to digital files. Soon the
processes themselves will be reevaluated and updated as necessary.
This work is significant because if the time spent on administrative work is decreased, the
band will have more time to spend on music and marching. This leads to a better band and a better
representation of the university. Additionally, the significance lies in giving students the opportunity to
practice and learn skills that will get them careers later on.
Reflecting on this project personally, I feel like I have learned an incredible amount. In working
with my advisor, I have had the opportunity to practice software development industry standards for
months. I understand more technical jargon and can relate more of the theoretical teachings that I
have learned in my classes than I ever would have from a standard classroom setting. That is in
addition to the technical skills that I have picked up in working with Microsoft PowerApps, GitHub, and
other connecting software. I feel that because of this project, I will have experiences that are
unmatched by others that may be competing with me as I begin searching for jobs. Finally, I am
unbelievably gratified at the legacy this project will leave for the OM&IS department and for the
Huskie Marching Band. This will continue to help students and staff in both groups for years to come

**Comment by fedebassetti** [comment]
[kick off presentation material](https://niuits-my.sharepoint.com/:p:/g/personal/z1801262_students_niu_edu/EbJ8lyKPgB1Ehp8DIgeSbBMBS3I4smPdrV1HijjuYSJ_Ug?e=4%3aOZnIBr&at=31)

**Comment by fedebassetti** [comment]
@cwalters126 the info is here together with the power point kick-off. We should have enough to put together an introductory story.

**Comment by leenabusalem** [comment]
is there a story posted somewhere that i can link for "more information" @fedebassetti

**Comment by fedebassetti** [comment]
@leenabusalem No, that is the first of its kind.
It does make sense to have the project description cards, but at the moment we don’t have anything else in place

**Comment by leenabusalem** [comment]
@fedebassetti i wanted to include a picture of eugene but the size is all weird. I also am having issues pushing back up

**Comment by fedebassetti** [comment]
@leenabusalem we can use what we learned yesterday and use the github or Linkedin images in place

**Comment by fedebassetti** [comment]
if not this might help [https://hm.dsp-niu.org/brother_pics/Eugene_Ciesla1317.jpg](https://hm.dsp-niu.org/brother_pics/Eugene_Ciesla1317.jpg)

**Comment by fedebassetti** [comment]
@leenabusalem here is the github https://github.com/eugeneciesla there is a new picture!

**Comment by leenabusalem** [comment]
@fedebassetti i used that github one, but when i modify sizes on the md, NO MATTER WHAT!! it looks strange. Sorry Eugene :)
![image](https://user-images.githubusercontent.com/59972338/85449504-705dc180-b55d-11ea-84ae-77d2446451b0.png)
![image](https://user-images.githubusercontent.com/59972338/85449547-7bb0ed00-b55d-11ea-9c9a-aaa2a5124b9b.png)

**Comment by fedebassetti** [comment]
@leenabusalem are you ready for this? 

only with use markdown

![gene](https://github.com/eugeneciesla.png?size=10)

![gene](https://github.com/eugeneciesla.png?size=40)

![gene](https://github.com/eugeneciesla.png?size=60)

![gene](https://github.com/eugeneciesla.png?size=100)

![gene](https://github.com/eugeneciesla.png?size=200)

![gene](https://github.com/eugeneciesla.png?size=100percent)

**Comment by leenabusalem** [comment]
im speechless but also confused on HOW

**Comment by fedebassetti** [comment]
@leenabusalem edit the comment i posted so you can see the code
